# This workflow deploys ApigeeX API Proxies

name: Deploy ApigeeX Proxies

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - sit
    paths:
      - "apiproxies/**"
  pull_request:
    branches:
      - sit
    paths:
      - "apiproxies/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect Changes to API Proxies
    # This job detects which proxies have changed since the last commit
    runs-on: ubuntu-latest

    outputs:
      changed_proxies: ${{ steps.set-proxies.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed
        run: |
          echo "Detecting changed files..."
          echo "Event name: ${{ github.event_name }}"

          # Compare with the base commit (for PRs) or previous SHA (for push)
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE=${{ github.event.pull_request.base.sha }}
          else
            BASE=${{ github.event.before }}
          fi

          CHANGED=$(git diff --name-only "$BASE" ${{ github.sha }} | xargs)

          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Extract changed API Proxy folders
        id: set-proxies
        run: |
          FILES="${{ steps.changed.outputs.changed_files }}"

          PROXIES=$(echo "$FILES" | tr ' ' '\n' | grep '^apiproxies/' | cut -d/ -f2 | sort -u | jq -R . | jq -s .)
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$PROXIES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  deploy-proxies:
    name: Deploy Changed Proxies
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_proxies != '[]'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'dev' || github.ref_name }}
    env:
      APIGEE_X_ORG: ${{ vars.APIGEE_X_ORG }}
      APIGEE_X_ENVS: "eval"
    strategy:
      matrix:
        proxy: ${{ fromJson(needs.detect-changes.outputs.changed_proxies) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get Environments
        id: get-envs
        run: |
          # Get the environments from the CONFIG file, else default to APIGEE_X_ENVS environment variable in job

          if [ -f "apiproxies/${{ matrix.proxy }}/CONFIG.yaml" ]; then
            APIGEE_X_ENVS=$(yq eval '.apiproxy.environments | join(" ")' "apiproxies/${{ matrix.proxy }}/CONFIG.yaml")
            echo "APIGEE_X_ENVS=$APIGEE_X_ENVS" >> "$GITHUB_ENV"
          fi

      - name: Apigee Environments
        run: echo "The value is $APIGEE_X_ENVS"

      - name: Get Service Account
        id: get-sa
        run: |
          # Get the service account from the CONFIG file, else default n

          if [ -f "apiproxies/${{ matrix.proxy }}/CONFIG.yaml" ]; then
            APIGEE_X_SA=$(yq eval '.apiproxy.serviceAccount' "apiproxies/${{ matrix.proxy }}/CONFIG.yaml")
            echo "APIGEE_X_SA=$APIGEE_X_SA" >> "$GITHUB_ENV"
          fi

      - name: Apigee SA
        run: echo "The value is $APIGEE_X_SA"

      # The committed changes may have deleted the proxy folder, so we need to check whether it still exists
      # If it does, then we proceed with the deployment
      # If it does not, we undeploy the proxy from all environments

      - name: Check if proxy folder exists
        id: check_folder
        run: |
          if [ -d "apiproxies/${{ matrix.proxy }}/apiproxy" ]; then
            echo "Proxy Folder exists"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Folder does not exist"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.APIGEE_SA_KEY }}"

      - name: Install Apigee CLI
        run: |
          curl -sLO https://github.com/apigee/apigeecli/releases/download/v2.15.0/apigeecli_v2.15.0_Linux_x86_64.zip
          unzip apigeecli_v2.15.0_Linux_x86_64.zip
          sudo mv apigeecli_v2.15.0_Linux_x86_64/apigeecli /usr/local/bin/

      - name: Install apigeelint
        if: steps.check_folder.outputs.exists == 'true'
        run: |
          npm install -g apigeelint

      - name: Output Deployment Info
        if: steps.check_folder.outputs.exists == 'true'
        run: |
          echo "Deployed ${{ matrix.proxy }} to environments $APIGEE_X_ENVS in project $APIGEE_X_ORG from branch ${{ github.ref_name }}"

      - name: Run apigeelint
        if: steps.check_folder.outputs.exists == 'true'
        run: |
          # set maxWarnings to -1 to ignore warnings, otherwise set to a number to fail build if the number of warnings is exceeded
          apigeelint -s ./apiproxies/${{ matrix.proxy }}/apiproxy -f stylish --maxWarnings 10

      - name: Create API Proxy bundle
        if: steps.check_folder.outputs.exists == 'true'
        run: |
          mkdir bundle
          cd apiproxies/${{ matrix.proxy }}
          zip -r ../../bundle/${{ matrix.proxy }}.zip apiproxy

      - name: Import ApigeeX Proxy
        if: steps.check_folder.outputs.exists == 'true'
        id: import
        run: |
          apigeecli apis import --default-token -o "$APIGEE_X_ORG"  --folder ./bundle
          REVISION=$(apigeecli apis get --default-token -o "$APIGEE_X_ORG" --name ${{ matrix.proxy }} | jq -r '.latestRevisionId')
          echo "revision=$REVISION" >> "$GITHUB_OUTPUT"

      - name: Deploy ApigeeX Proxy
        if: steps.check_folder.outputs.exists == 'true'
        run: |
          echo "Deploying revision ${{ steps.import.outputs.revision }}"
          for APIGEE_X_ENV in $APIGEE_X_ENVS; do
            if [ -z "$APIGEE_X_SA" ] || [ "$APIGEE_X_SA" = "null" ]; then
              echo "No service account specified, deploying without service account"
              apigeecli apis deploy --default-token -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --name "${{ matrix.proxy }}" --rev ${{ steps.import.outputs.revision }} --ovr
            else
              echo "Using service account: $APIGEE_X_SA"
              apigeecli apis deploy --default-token -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --name "${{ matrix.proxy }}" --rev ${{ steps.import.outputs.revision }} --ovr --sa "$APIGEE_X_SA"
            fi
          done

      # The committed changes have deleted the proxy, so we undeploy the proxy from all environments
      - name: Undeploy Deleted Proxies
        if: steps.check_folder.outputs.exists == 'false'
        run: |
          set +e  # disable immediate exit on error
          echo "Proxy ${{ matrix.proxy }} does not exist. Undeploying from all Environments."
          ENVS=$(apigeecli environments list --default-token -o "$APIGEE_X_ORG"  | jq -r '. | join(" ")')
          for APIGEE_X_ENV in $ENVS; do
            OUTPUT=$(apigeecli apis undeploy --default-token -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --name "${{ matrix.proxy }}")
            STATUS=$?

            if [ "$STATUS" -eq 0 ]; then
              echo "✅ Success"
            elif echo "$OUTPUT" | grep -q "is not deployed"; then
              echo "ℹ️ Proxy is not deployed to this environment, so treating as success"
            else
              echo "❌ Unexpected error"
              exit $STATUS
            fi
          done

      - name: Remove Deleted Proxies
        if: steps.check_folder.outputs.exists == 'false'
        run: |
          echo "Proxy ${{ matrix.proxy }} does not exist. Deleting from Organization."
          # TODO: Add logic to delete the proxy from the organization
